### ISSUE TITLE
Result score, not returning

### ISSUE THREAD

**Issue by kashmiry** [freearhey/knowledge-graph#1]
Hello,
for some reason in the last version 2.0 
the result don't return the score!

`$results = $graph->search($searchQuery, 'Person', 'en,ar', 3);
var_dump($results );`

each result should have a score like this
`["score"]=> float(171.995575)`

Any idea how I can get it.

**Comment by freearhey** [comment]
Hi,

Now there is no score value at all, but I will try to add it to the search result in the next update.

**Comment by freearhey** [comment]
Done.
